Misc fixes.
- Use password cache is available.
- Do not check for the repository unless --check is provided.
- Do not fetch all branches every time.

diff --git a/git-cms-init b/git-cms-init
--- a/git-cms-init
+++ b/git-cms-init
@@ -46,6 +46,8 @@ while [ "$#" != 0 ]; do
       shift; USE_HTTPS_ACCESS_METHOD=true ;;
     --ssh )
       shift; USE_SSH_ACCESS_METHOD=true ;;
+    --check )
+      shift; DO_CHECK=true ;;
     -*)
       echo Unknown option $1 ; usage 1 ;;
     *)
@@ -64,6 +66,7 @@ done
 USER_FULLNAME="`git config --global --get user.name || true`"
 USER_EMAIL="`git config --global --get user.email || true`"
 GITHUB_USERNAME="`git config --global --get user.github || true`"
+
 if [ -z "$GITHUB_USERNAME" ] || [ -z "$USER_FULLNAME" ] || [ -z "$USER_EMAIL" ]; then
   echo "Cannot find your details in the git configuration."
   if [ "X$USER_FULLNAME" = X ]; then
@@ -225,50 +228,53 @@ if [ -e $CMSSW_GIT_REFERENCE/create-`whoami` ]; then
 fi
 
 # check the user setup on GitHub
-if curl -s "https://api.github.com/users/$GITHUB_USERNAME" | tee $DEBUG_STREAM | grep -q -i 'Not Found' ; then
-  $ECHO "You don't seem to have a GitHub accout, or your GitHub username ($RED$GITHUB_USERNAME$NORMAL) is not correct." > $VERBOSE_STREAM
-  $ECHO "($RED$GITHUB_USERNAME$NORMAL) is not correct."                                                     > $VERBOSE_STREAM
-  $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
-  $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "You can correct your GitHub user name via:"                                                        > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "    git config --global user.github <your github username>"                                        > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "To create a personal repository:"                                                                  > $VERBOSE_STREAM
-  $ECHO "    visit to https://github.com/ and register a new account"                                       > $VERBOSE_STREAM
-  $ECHO "    visit to https://github.com/cms-sw/cmssw and click on the Fork button"                         > $VERBOSE_STREAM
-  $ECHO "    select the option to fork the repository under your username ($RED$GITHUB_USERNAME$NORMAL)"    > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  USER_CMSSW_REPO=""
-elif ! curl -s "https://api.github.com/users/$GITHUB_USERNAME/repos" | tee $DEBUG_STREAM | grep -q '"name": *"cmssw"'; then
-  $ECHO "You don't seem to have a personal repository, or your GitHub username ($RED$GITHUB_USERNAME$NORMAL) is not correct." > $VERBOSE_STREAM
-  $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
-  $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "You can correct your GitHub user name via:"                                                        > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "    git config --global user.github <your github username>"                                        > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "To create a personal repository:"                                                                  > $VERBOSE_STREAM
-  $ECHO "  - go to https://github.com/ and log in"                                                          > $VERBOSE_STREAM
-  $ECHO "  - go to https://github.com/cms-sw/cmssw and click on the Fork button"                            > $VERBOSE_STREAM
-  $ECHO "  - select the option to fork the repository under your username ($RED$GITHUB_USERNAME$NORMAL)"    > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  USER_CMSSW_REPO=""
-elif ! git ls-remote $USER_CMSSW_REPO >& $DEBUG_STREAM; then
-  $ECHO "Your GitHub account ($RED$GITHUB_USERNAME$NORMAL) and personal repository ($RED$USER_CMSSW_REPO$NORMAL) " > $VERBOSE_STREAM
-  $ECHO "look properly configured, but git is unable to access it."                                         > $VERBOSE_STREAM
-  $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
-  $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  USER_CMSSW_REPO=""
+if [ ! X"$DO_CHECK" = X ]; then
+  if curl -s "https://api.github.com/users/$GITHUB_USERNAME" | tee $DEBUG_STREAM | grep -q -i 'Not Found' ; then
+    $ECHO "You don't seem to have a GitHub accout, or your GitHub username ($RED$GITHUB_USERNAME$NORMAL) is not correct." > $VERBOSE_STREAM
+    $ECHO "($RED$GITHUB_USERNAME$NORMAL) is not correct."                                                     > $VERBOSE_STREAM
+    $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
+    $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "You can correct your GitHub user name via:"                                                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "    git config --global user.github <your github username>"                                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "To create a personal repository:"                                                                  > $VERBOSE_STREAM
+    $ECHO "    visit to https://github.com/ and register a new account"                                       > $VERBOSE_STREAM
+    $ECHO "    visit to https://github.com/cms-sw/cmssw and click on the Fork button"                         > $VERBOSE_STREAM
+    $ECHO "    select the option to fork the repository under your username ($RED$GITHUB_USERNAME$NORMAL)"    > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    USER_CMSSW_REPO=""
+  elif ! curl -s "https://api.github.com/users/$GITHUB_USERNAME/repos" | tee $DEBUG_STREAM | grep -q '"name": *"cmssw"'; then
+    $ECHO "You don't seem to have a personal repository, or your GitHub username ($RED$GITHUB_USERNAME$NORMAL) is not correct." > $VERBOSE_STREAM
+    $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
+    $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "You can correct your GitHub user name via:"                                                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "    git config --global user.github <your github username>"                                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "To create a personal repository:"                                                                  > $VERBOSE_STREAM
+    $ECHO "  - go to https://github.com/ and log in"                                                          > $VERBOSE_STREAM
+    $ECHO "  - go to https://github.com/cms-sw/cmssw and click on the Fork button"                            > $VERBOSE_STREAM
+    $ECHO "  - select the option to fork the repository under your username ($RED$GITHUB_USERNAME$NORMAL)"    > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    USER_CMSSW_REPO=""
+  elif ! git ls-remote $USER_CMSSW_REPO >& $DEBUG_STREAM; then
+    $ECHO "Your GitHub account ($RED$GITHUB_USERNAME$NORMAL) and personal repository ($RED$USER_CMSSW_REPO$NORMAL) " > $VERBOSE_STREAM
+    $ECHO "look properly configured, but git is unable to access it."                                         > $VERBOSE_STREAM
+    $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
+    $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    USER_CMSSW_REPO=""
+  fi
 fi
 
 mkdir -p $CMSSW_BASE/src
 cd $CMSSW_BASE/src
+
 if [ ! -d "$CMSSW_BASE/src/.git" ]; then
   # clone the official repository from $OFFICIAL_CMSSW_REPO, using $CMSSW_GIT_REFERENCE as a local reference, inside $CMSSW_BASE/src
   # name the remote repository "official-cmssw"
@@ -299,6 +305,15 @@ if [ ! -d "$CMSSW_BASE/src/.git" ]; then
   echo "${LEADING_SLASH}.gitignore" > $CMSSW_BASE/src/.git/info/sparse-checkout
   git checkout $CMSSW_BRANCH -- .gitignore
   git read-tree -mu HEAD
+fi
+
+# Avoid asking for password for 24 hours.
+GIT_CREDENTIAL_CACHE="`git config --get credential.cache || true`"
+if [ "X$GIT_CREDENTIAL_CACHE" = X ]; then
+  case `uname` in
+    Darwin*) git config --add credential.cache osxkeychain ;;
+    Linux*) git config --add credential.cache "cache --timeout=86400 --socket $TMPDIR/.git-credential-cache-socket" ;;
+  esac
 fi
 
 verbose You are on branch `git symbolic-ref --short HEAD`
